[package]
name = "supertokens_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1.35.1"
serde = { version = "1.0.194", features = ["derive"] }
reqwest = { version = "0.11.23", features = ["json"] }
serde_json = "1.0.111"
